adb_versions/adb_Practicas/routes/web.php
<?php

// Se tiene 3 middlewares
// Administrador
// Usuario 
// Administrador&Usuario
// Según la necesidad de la ruta se le asigna middleware al método

Auth::routes();

Route::get('/', 'HomeController@wellcome')->name('wellcome');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/goal', 'HomeController@goal')->name('goal');
Route::get('/mailus', 'HomeController@mailus')->name('mailus');

Route::resource('/report', 'AreaCompanieController')->middleware('auth');
Route::resource('/idtype', 'IdTypeController')->middleware('admin');
Route::resource('/role', 'RoleController')->middleware('admin');
Route::resource('/user', 'UserController')->middleware('admin');
Route::resource('/companie', 'CompanieController')->middleware('admin');
Route::resource('/area', 'AreaController')->middleware('admin');
Route::resource('/document', 'DocumentController')->middleware('admin');
Route::resource('/comment', 'CommentController')->middleware('adminuser');
Route::resource('/contact', 'ContactController')->middleware('admin');

adb_versions/adb_Practicas/app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    public function companies(){
        return $this->belongsToMany(Companie::class, 'areas_companies');
    }  

    public function areacompanies(){
        return $this->hasMany(AreaCompanie::class);
    }  
    
    protected $table = 'areas';

    protected $fillable = [
        'name', 'body', 
    ];
}

adb_versions/adb_Practicas/app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use App\Area;
use Illuminate\Http\Request;

class AreaController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $areas = Area::orderBy('created_at', 'desc')->paginate(10);
        return view('areas.index', compact('areas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('areas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            'name' => 'required|string|max:45',
            'body' => 'required|string|max:200'
        ]);
        $area = new Area();
        $area->name = $request->name;
        $area->body = $request->body;
        $area->save();

        return redirect()->route('area.index')->with('statusC', 'Area '.$area->name.' Creada!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function show(Area $area)
    {
        return $area;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function edit(Area $area)
    {
        return view('areas.edit', compact('area'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Area $area)
    {
        $validateData = $request->validate([
            'name' => 'required|string|max:45',
            'body' => 'required|string|max:200'
        ]);
        $area->name = $request->name;
        $area->body = $request->body;
        $area->save();

        return redirect()->route('area.index')->with('statusU', 'Area '.$area->name.' Editada!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function destroy(Area $area)
    {
        $area->delete();
        return redirect()->route('area.index')->with('statusD', 'Area '.$area->name.' Eliminada!');
    }
    
}

adb_versions/adb_Practicas/resources/views/areas/create.blade.php
@extends('layouts.appBack')

@section('content')
    {{-- bread --}}
    <nav aria-label="breadcrumb" class="my-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{route('idtype.index')}}">Áreas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nueva Área</li>
        </ol>
    </nav>
    {{-- endbread --}}
    <h1 class="my-5 text-center">Registrar Área</h1> 
    
    <div class="card p-5 m-2">

        <div class="mb-5">
            <a href="{{route('area.index')}}"><i class="fa fa-hand-o-left" aria-hidden="true"></i> Regresar</a>
        </div>

            <form method="POST" action="{{ route('area.store') }}">
                @csrf

                <div class="row">
                    <div class="form-group col-md-12">
                        <input placeholder="Nombre" id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>                   
                </div>        

                <div class="row">
                    <div class="form-group col-md-12">
                        <textarea placeholder="Descipción" id="body" class="form-control @error('body') is-invalid @enderror" name="body" required autocomplete="new-body"></textarea>
                        @error('body')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="form-group col text-center">
                        <button type="submit" class="btn btn-dark">
                            {{ __('Registrar') }}
                        </button>
                    </div>                
                </div>

            </form>

        </div>
    </div>
@endsection

adb_versions/adb_Practicas/resources/views/areas/edit.blade.php
@extends('layouts.appBack')

@section('content')
    {{-- bread --}}
    <nav aria-label="breadcrumb" class="my-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{route('idtype.index')}}">Áreas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar {{$area->name}}</li>
        </ol>
    </nav>
    {{-- endbread --}}
    <h1 class="my-5 text-center">Editar {{$area->name}}</h1> 
    
    <div class="card p-5 m-2">
            
        <div class="mb-5">
            <a href="{{route('area.index')}}"><i class="fa fa-hand-o-left" aria-hidden="true"></i> Regresar</a>
        </div>

        <form method="POST" action="{{ route('area.update', $area) }}">
            @method('PUT')
            @csrf

            <div class="row">
                    <div class="form-group col-md-12">
                        <input value="{{$area->name}}" placeholder="Nombre" id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>                   
                </div>        

                <div class="row">
                    <div class="form-group col-md-12">
                        <textarea placeholder="Descipción" id="body" class="form-control @error('body') is-invalid @enderror" name="body" required autocomplete="new-body">{{$area->body}}</textarea>
                        @error('body')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="form-group col text-center">
                        <button type="submit" class="btn btn-dark">
                            {{ __('Editar') }}
                        </button>
                    </div>                
                </div>
        </form>

    </div>
@endsection

adb_versions/adb_Practicas/resources/views/areas/index.blade.php
@extends('layouts.appBack')
    @section('content')
        {{-- bread --}}
        <nav aria-label="breadcrumb" class="my-4">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
                <li class="breadcrumb-item active" aria-current="page">Áreas</li>
            </ol>
        </nav>
        {{-- endbread --}}
        <h1 class="my-5 text-center">Áreas</h1>
         
        <div class="card p-4">

            <div class="mb-4 container-fluid">
                <a class="btn btn-dark" href="{{route('area.create')}}">Nuevo</a>
            </div>

            @include('partials.session_status')

            <div class="container-fluid max-auto">
                <table class="table table-hover table-striped table-responsive-xl border">
                    <thead>
                        <tr>
                            <th>Nombre</th>                        
                            <th>Descripción</th>
                            <th width="5%"class="text-center">Editar</th> 
                            <th width="5%"class="text-center">Eliminar</th>                                
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($areas as $key=>$area)
                        <tr>
                            <td>{{$area->name}}</td>
                            <td>{{$area->body}}</td>
                            <td class="text-center">
                                <a href="{{route('area.edit', $area)}}" class="btn btn-sm"><i class="fa fa-pencil text-warning" aria-hidden="true"></i></a>
                            </td>
                            <td class="text-center">
                                <form class="d-inline" action="{{route('area.destroy', $area)}}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm"><i class="fa fa-ban text-danger" aria-hidden="true"></i></button>
                                </form>
                                {{-- <a href="{{route('user.destroy', $user)}}" class="btn btn-sm"><i class="fa fa-ban text-danger" aria-hidden="true"></i></a> --}}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$areas}} 
            </div>
        </div>      
    @endsection