adb_versions/adb_Practicas/routes/web.php
<?php

// Se tiene 3 middlewares
// Administrador
// Usuario 
// Administrador&Usuario
// Según la necesidad de la ruta se le asigna middleware al método

Auth::routes();

Route::get('/', 'HomeController@wellcome')->name('wellcome');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/goal', 'HomeController@goal')->name('goal');
Route::get('/mailus', 'HomeController@mailus')->name('mailus');

Route::resource('/report', 'AreaCompanieController')->middleware('auth');
Route::resource('/idtype', 'IdTypeController')->middleware('admin');
Route::resource('/role', 'RoleController')->middleware('admin');
Route::resource('/user', 'UserController')->middleware('admin');
Route::resource('/companie', 'CompanieController')->middleware('admin');
Route::resource('/area', 'AreaController')->middleware('admin');
Route::resource('/document', 'DocumentController')->middleware('admin');
Route::resource('/comment', 'CommentController')->middleware('adminuser');
Route::resource('/contact', 'ContactController')->middleware('admin');

adb_versions/adb_Practicas/app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    public function report(){
        return $this->belongsTo(AreaCompanie::class, 'area_companie_id');
    }
    
    protected $table = 'documents';

    protected $fillable = [
        'path', 'status', 'name', 'area_companie_id',
    ];
}

adb_versions/adb_Practicas/app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use Illuminate\Http\Request;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $documents = Document::orderBy('created_at', 'desc')->paginate(10);
        return view('documents.index', compact('documents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('documents.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            'name' => 'required|string|max:45',
            'file' => 'required|file',
            'area_companie_id' => 'required|integer',
            'status' => 'required|string',
        ]);
        // dd($request->file('path'));
        if($request->hasFile('path')){
            $file = $request->file('path');
            $name = time().$file->getClientOriginalName();
            $file->move(public_path().'/documents/', $name);
        }
        $document = new Document();
        $document->area_companie_id = $request->area_companie_id;
        $document->name = $request->name;
        $document->path = $name;
        $document->status = $request->status;
        $document->save();

        return redirect()->route('document.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        $path = 'documents/'.$document->path;
        return response()->download($path);
        // return response()->download($path);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        return view('documents.edit', compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $document)
    {
        if($request->hasFile('path')){
            $file = $request->file('path');
            $name = time().$file->getClientOriginalName();
            $file->move(public_path().'/documents/', $name);
        }
        $document->area_companie_id = $request->area_companie_id;
        $document->name = $request->name;
        $document->path = $name;
        $document->save();

        return redirect()->route('document.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function destroy(Document $document)
    {
        if($document->status == 'ACTIVO'){
            $document->status = 'INACTIVO';
        }elseif($document->status == 'INACTIVO'){
            $document->status = 'ACTIVO';
        }        
        $document->save();
        return redirect()->route('document.index');
    }
}

adb_versions/adb_Practicas/resources/views/documents/create.blade.php
@extends('layouts.appBack')

@section('content')
    {{-- bread --}}
    <nav aria-label="breadcrumb" class="my-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{route('document.index')}}">Documentos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nuevo Documento</li>
        </ol>
    </nav>
    {{-- endbread --}}
    <h1 class="my-5 text-center">Registrar Documento</h1> 
    
    <div class="card m-2 p-5">

        <div class="mb-5">
            <a href="{{route('document.index')}}"><i class="fa fa-hand-o-left" aria-hidden="true"></i> Regresar</a>
        </div>

        <form method="POST" action="{{ route('document.store') }}" enctype="multipart/form-data">
            @csrf

            <div class="row">
                <div class="form-group col">
                    <input type="text" id="name" class="form-control @error('name') is-invalid @enderror" name="name" required autocomplete="new-body" placeholder="Nombre">
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>                        
            </div> 

            <div class="row">

                <div class="form-group col-12">                            
                    <select id="area_companie_id" class="form-control @error('area_companie_id') is-invalid @enderror" name="area_companie_id" required >
                            <option value="" selected disabled>Reporte</option>
                        @foreach($reports as $report)
                            <option value="{{$report->id}}">{{$report->body}}</option>
                        @endforeach
                    </select>
                    @error('area_companie_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>                        
                
            </div>     

            <div class="row border m-1">
                <div class="form-group col-12 d-inline">
                    <label for="path">Archivo</label> 
                    <input type="file" name="path" class="form-control-file" id="path">
                </div>
                @error('path')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>   

            <div class="row mt-5">
                <div class="form-group col text-center">
                    <button type="submit" class="btn btn-dark">
                        {{ __('Registrar') }}
                    </button>
                </div>                
            </div>

        </form>

    </div>
@endsection

adb_versions/adb_Practicas/resources/views/documents/edit.blade.php
@extends('layouts.appBack')

@section('content')

    {{-- bread --}}
    <nav aria-label="breadcrumb" class="my-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{route('document.index')}}">Documentos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Empresa</li>
        </ol>
    </nav>
    {{-- endbread --}}

    <h1 class="my-5 text-center">Editar Documento {{$document->name}}</h1> 
    
    <div class="p-5 m-2 card">

        <div class="mb-5">
            <a href="{{route('document.index')}}"><i class="fa fa-hand-o-left" aria-hidden="true"></i> Regresar</a>
        </div>

        <form method="POST" action="{{ route('document.update', $document) }}">
            @method('PUT')
            @csrf

            <div class="row">

                <div class="form-group col">
                    <input value="{{$document->name}}" type="text" id="name" class="form-control @error('name') is-invalid @enderror" name="name" required autocomplete="new-body" placeholder="Nombre">
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>  

            </div> 
    
            <div class="row">

                <div class="form-group col-12">                            
                    <select id="area_companie_id" class="form-control @error('area_companie_id') is-invalid @enderror" name="area_companie_id" required >
                            <option value="" selected disabled>Reporte</option>
                        @foreach($reports as $report)
                            <option value="{{$report->id}}">{{$report->body}}</option>
                        @endforeach
                    </select>
                    @error('area_companie_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>                        
                
            </div>     

            <div class="row border m-1">

                <div class="form-group col-12 d-inline">
                    <label for="image">Editar Archivo: </label>
                    <input type="file" name="image" id='image' class="@error('image') is-invalid @enderror form-control-file" placeholder="archivo">
                    @error('image')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

            </div>
    
            <div class="row mt-5">
                <div class="form-group col text-center">
                    <button type="submit" class="btn btn-dark">
                        {{ __('Editar') }}
                    </button>
                </div>                
            </div>
            
        </form>

    </div>

@endsection

adb_versions/adb_Practicas/resources/views/documents/index.blade.php
@extends('layouts.appBack')
    @section('content')
        {{-- bread --}}
        <nav aria-label="breadcrumb" class="my-4">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
                <li class="breadcrumb-item active" aria-current="page">Documentos</li>
            </ol>
        </nav>
        {{-- endbread --}}
        <h1 class="my-5 text-center">Control Documentos</h1>          
         
        <div class="card p-4">

            <div class="mb-4 container-fluid">
                <a class="btn btn-dark" href="{{route('document.create')}}">Nuevo</a>
            </div>
            
            <div class="container-fluid mx-auto">
                <table class="table table-hover table-striped table-responsive-xl border">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Reporte</th>
                            <th>Empresa</th>
                            <th>Área</th>
                            <th>Fecha Creación</th>    
                            <th width="5%"class="text-center">Editar</th> 
                            <th width="5%"class="text-center">Estado</th>                                
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($documents as $key=>$document)
                        <tr>
                            <td><a href="documents/{{$document->path}}">{{$document->name}}</a></td>
                            <td>{{$document->report->body}}</td>
                            <td>{{$document->report->companie->name}}</td>
                            <td>{{$document->report->area->name}}</td>
                            <td>{{$document->created_at->day}}/{{$document->created_at->month}}/{{$document->created_at->year}}</td>
                            <td class="text-center">
                                <a href="{{route('document.edit', $document)}}" class="btn btn-sm"><i class="fa fa-pencil text-warning" aria-hidden="true"></i></a>
                            </td>
                            <td class="text-center">
                                <form class="d-inline" action="{{route('document.destroy', $document)}}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm">
                                        @if($document->status == 'ACTIVO')
                                        <i class="fa fa-toggle-on text-success" aria-hidden="true"></i>
                                        @else
                                        <i class="fa fa-toggle-on text-danger" aria-hidden="true"></i>
                                        @endif
                                    </button>
                                </form>
                                {{-- <a href="{{route('user.destroy', $user)}}" class="btn btn-sm"><i class="fa fa-ban text-danger" aria-hidden="true"></i></a> --}}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            {{$documents}} 
            </div>           
        </div>      
    @endsection