adb_versions/adb_Practicas/routes/web.php
<?php

// Se tiene 3 middlewares
// Administrador
// Usuario 
// Administrador&Usuario
// Según la necesidad de la ruta se le asigna middleware al método

Auth::routes();

Route::get('/', 'HomeController@wellcome')->name('wellcome');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/goal', 'HomeController@goal')->name('goal');
Route::get('/mailus', 'HomeController@mailus')->name('mailus');

Route::resource('/report', 'AreaCompanieController')->middleware('auth');
Route::resource('/idtype', 'IdTypeController')->middleware('admin');
Route::resource('/role', 'RoleController')->middleware('admin');
Route::resource('/user', 'UserController')->middleware('admin');
Route::resource('/companie', 'CompanieController')->middleware('admin');
Route::resource('/area', 'AreaController')->middleware('admin');
Route::resource('/document', 'DocumentController')->middleware('admin');
Route::resource('/comment', 'CommentController')->middleware('adminuser');
Route::resource('/contact', 'ContactController')->middleware('admin');

adb_versions/adb_Practicas/app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    public function report(){
        return $this->belongsTo(AreaCompanie::class, 'area_companie_id');
    }
    
    protected $table = 'comments';

    protected $fillable = [
        'body', 'area_companie_id', 'status'
    ];
}

adb_versions/adb_Practicas/app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{     
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::orderBy('created_at', 'desc')->paginate(10);
        return view('comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('comments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            'body' => 'required|string||max:200',
            'area_companie_id' => 'required|string',
        ]);
        $comm = new Comment();
        $comm->area_companie_id = $request->area_companie_id;
        $comm->body = $request->body;
        $comm->status = 'ACTIVO';
        $comm->save();

        return redirect()->back()->with('statusC', 'Comentario Creado');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        // return $comment;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        return view('comments.edit', compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        $validateData = $request->validate([
            'body' => 'required|string||max:200',
            'area_companie_id' => 'required|string',
        ]);
        $comment->area_companie_id = $request->area_companie_id;
        $comment->body = $request->body;
        $comment->save();

        return redirect()->back()->with('statusU', 'Comentario Editado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        if($comment->status == 'ACTIVO'){
            $comment->status = 'INACTIVO';
        }elseif($comment->status == 'INACTIVO'){
            $comment->status = 'ACTIVO';
        }        
        $comment->save();

        return redirect()->back()->with('statusU', 'Estado del comentario Cambiado');
    }
}

adb_versions/adb_Practicas/resources/views/comments/create.blade.php
@extends('layouts.appBack')

@section('content')
    {{-- bread --}}
    <nav aria-label="breadcrumb" class="my-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{route('comment.index')}}">Comentarios</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nuevo comentario</li>
        </ol>
    </nav>
    {{-- endbread --}}
    <h1 class="my-5 text-center">Registrar Comentario</h1> 
    
    <div class="card m-2 p-5">

            <div class="mb-5">
                <a href="{{route('comment.index')}}"><i class="fa fa-hand-o-left" aria-hidden="true"></i> Regresar</a>
            </div>

            <form method="POST" action="{{ route('comment.store') }}">
                @csrf

                <div class="row">

                    <div class="form-group col-12">
                        
                        <select id="area_companie_id" class="form-control @error('area_companie_id') is-invalid @enderror" name="area_companie_id" required >
                                <option value="" selected disabled>Empresa y Área del Reporte</option>
                            @foreach($reports as $report)
                                <option value="{{$report->id}}">{{$report->companie->name.' '.$report->area->name.' | '.$report->body}}</option>
                            @endforeach
                        </select>
                        
                        @error('area_companie_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror

                    </div>
                </div> 

                <div class="row">

                    <div class="form-group col-12">
                        <textarea id="body" class="form-control @error('body') is-invalid @enderror" name="body" required autocomplete="new-body"></textarea>
                        @error('body')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror

                    </div>
                </div> 

                <div class="row mt-5">
                    <div class="form-group col text-center">
                        <button type="submit" class="btn btn-dark">
                            {{ __('Registrar') }}
                        </button>
                    </div>                
                </div>

            </form>

        </div>
        
@endsection

adb_versions/adb_Practicas/resources/views/comments/edit.blade.php
@extends('layouts.appBack')
@section('content')
    {{-- bread --}}
    <nav aria-label="breadcrumb" class="my-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{route('comment.index')}}">Comentarios</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Comentario</li>
        </ol>
    </nav>
    {{-- endbread --}}
    <h1 class="my-5 text-center">Editar Comentario</h1>     
    <div class="card m-2 p-5">
        <div class="mb-5">
            <a href="{{route('comment.index')}}"><i class="fa fa-hand-o-left" aria-hidden="true"></i> Regresar</a>
        </div>           
        <form method="POST" action="{{ route('comment.update', $comment) }}">
            @csrf
            @method('PUT')

            <div class="row">
                <div class="form-group col-12">
                    
                    <select id="area_companie_id" class="form-control @error('area_companie_id') is-invalid @enderror" name="area_companie_id" required >
                        @foreach($reports as $report)
                            @if($comment->report->id == $report->id)
                                <option value="{{$report->id}}" selected>{{$report->companie->name.' '.$report->area->name.' | '.$report->body}}</option>
                            @else
                                <option value="{{$report->id}}">{{$report->companie->name.' '.$report->area->name.' | '.$report->body}}</option>                                   
                            @endif
                        @endforeach
                    </select>
                    
                    @error('area_companie_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror

                </div>
            </div> 
            
            <div class="form-group row">                
                <div class="col-12">
                    <textarea id="body" class="form-control @error('body') is-invalid @enderror" name="body" required autocomplete="new-body">{{$comment->body}}</textarea>
                    @error('body')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror

                </div>
            </div> 

            <div class="row mt-5">
                <div class="form-group col text-center">
                    <button type="submit" class="btn btn-dark">
                        {{ __('Editar') }}
                    </button>
                </div>                
            </div>

        </form>
        
    </div>
@endsection

adb_versions/adb_Practicas/resources/views/comments/index.blade.php
@extends('layouts.appBack')
    @section('content')
        {{-- bread --}}
        <nav aria-label="breadcrumb" class="my-4">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Inicio</a></li>
                <li class="breadcrumb-item active" aria-current="page">Comentarios</li>
            </ol>
        </nav>
        {{-- endbread --}}
        <h1 class="my-5 text-center">Control Comentarios</h1>          
         
        <div class="card p-4">

            <div class="mb-4 container-fluid">
                <a class="btn btn-dark" href="{{route('comment.create')}}">Nuevo</a>
            </div>

            @include('partials.session_status')

            <div class="container-fluid mx-auto">
                <table class="table table-hover table-striped table-responsive-xl border">
                    <thead>
                        <tr>
                            <th>Reporte</th>
                            <th>Fecha Creación<th>
                            <th>Descripcion</th>
                            <th width="5%"class="text-center">Editar</th> 
                            <th width="5%"class="text-center">Estado</th>                                
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($comments as $key=>$comment)
                        <tr>
                            <td>{{$comment->report->companie->name}} | {{$comment->report->area->name}}</td>
                            <td>{{$comment->created_at}}<td>
                            <td>{{$comment->body}}</td>    
                            <td class="text-center">
                                <a href="{{route('comment.edit', $comment)}}" class="btn btn-sm"><i class="fa fa-pencil text-warning" aria-hidden="true"></i></a>
                            </td>
                            <td class="text-center">
                                <form class="d-inline" action="{{route('comment.destroy', $comment)}}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm">
                                        @if($comment->status == 'ACTIVO')
                                        <i class="fa fa-toggle-on text-success" aria-hidden="true"></i>
                                        @else
                                        <i class="fa fa-toggle-on text-danger" aria-hidden="true"></i>
                                        @endif
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$comments}}    
            </div>        
        </div>      
    @endsection